server:
  port: 8888


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    username: postgres
    password: Panha12345
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mobile_banking_cstad
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #  or create-drop
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /

file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"

#Configure datasource
